#!/usr/bin/env python3
"""
generate_summary.py
====================
Generates a concise Markdown summary report for GitHub Actions Step Summary
and the Test Results/Summary/summary.md artifact.
"""

import argparse
import xml.etree.ElementTree as ET
from pathlib import Path
from datetime import datetime


def parse_junit(junit_path: str) -> dict:
    result = {'total':0,'passed':0,'failed':0,'skipped':0,'errors':0,'duration':0.0,'tests':[]}
    if not Path(junit_path).exists():
        return result
    try:
        root = ET.parse(junit_path).getroot()
        suites = [root] if root.tag=='testsuite' else root.findall('testsuite')
        for suite in suites:
            for tc in suite.findall('testcase'):
                duration = float(tc.get('time','0') or '0')
                failure  = tc.find('failure')
                error    = tc.find('error')
                skipped  = tc.find('skipped')
                if failure is not None:
                    status, msg = 'FAILED',  (failure.get('message','') or failure.text or '')[:200]
                    result['failed'] += 1
                elif error is not None:
                    status, msg = 'ERROR',   (error.get('message','') or error.text or '')[:200]
                    result['errors'] += 1
                elif skipped is not None:
                    status, msg = 'SKIPPED', skipped.get('message','')
                    result['skipped'] += 1
                else:
                    status, msg = 'PASSED', ''
                    result['passed'] += 1
                result['total']    += 1
                result['duration'] += duration
                result['tests'].append({'name':tc.get('name','?'),'status':status,'msg':msg,'duration':round(duration,2)})
    except Exception as e:
        print(f'[WARN] {e}')
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--junit',    default='e2e/test-results/junit.xml')
    parser.add_argument('--base-url', default='https://Asanjay712.github.io/pddtesting/')
    parser.add_argument('--repo',     default='Asanjay712/pddtesting')
    parser.add_argument('--output',   default='Test Results/Summary/summary.md')
    args = parser.parse_args()

    data    = parse_junit(args.junit)
    total   = data['total']
    passed  = data['passed']
    failed  = data['failed'] + data['errors']
    skipped = data['skipped']
    pct     = round(passed/total*100,1) if total > 0 else 0
    dur     = round(data['duration'],2)
    now     = datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')

    status_icon = '✅' if failed == 0 else '❌'
    pct_icon    = '🟢' if pct >= 90 else '🟡' if pct >= 70 else '🔴'

    lines = [
        '# 🧪 Live GitHub Pages E2E Test Summary',
        '',
        f'**{status_icon} Status:** {"All tests passed!" if failed == 0 else f"{failed} test(s) failed"}  ',
        f'**📅 Date:** {now}  ',
        f'**🌐 Deployment URL:** [{args.base_url}]({args.base_url})  ',
        f'**📦 Repository:** [{args.repo}](https://github.com/{args.repo})  ',
        '',
        '---',
        '',
        '## 📊 Results',
        '',
        '| Metric | Value |',
        '|---|---|',
        f'| Total Tests  | **{total}** |',
        f'| ✅ Passed    | **{passed}** |',
        f'| ❌ Failed    | **{failed}** |',
        f'| ⏭️  Skipped   | **{skipped}** |',
        f'| {pct_icon} Pass Rate | **{pct}%** |',
        f'| ⏱️  Duration  | **{dur}s** |',
        '',
    ]

    if failed > 0:
        lines.append('## ❌ Failed Tests')
        lines.append('')
        lines.append('| Test Name | Error |')
        lines.append('|---|---|')
        for t in data['tests']:
            if t['status'] in ('FAILED', 'ERROR'):
                msg = t['msg'].replace('\n',' ').replace('|','\\|')[:200] if t['msg'] else 'See logs'
                lines.append(f'| {t["name"]} | {msg} |')
        lines.append('')

    lines += [
        '## 📁 Artifacts',
        '',
        '| Artifact | Description |',
        '|---|---|',
        '| `e2e-test-results` | Excel report, HTML report, screenshots, logs |',
        '| `playwright-html-report` | Interactive Playwright HTML report |',
        '',
        '---',
        '',
        f'*Generated by Medical AI Platform CI/CD Pipeline — {now}*',
    ]

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(lines), encoding='utf-8')
    print(f'[INFO] Summary saved: {out}')


if __name__ == '__main__':
    main()
